namespace NextGenSoftware.OASIS.API.Core.Enums
{
    //https://stexpanded.fandom.com/wiki/Planet_classifications
    //https://memory-alpha.fandom.com/wiki/Planetary_classification
    public enum PlanetClassification
    {
        ClassA,
        ClassB,
        ClassC,
        ClassD,
        ClassE,
        ClassF,
        ClassG,
        ClassH,
        ClassI,
        ClassJ,
        ClassK,
        ClassL,
        ClassM,
        ClassN,
        ClassO,
        ClassP,
        ClassQ,
        ClassR,
        ClassT,
        ClassX,
        ClassY,
        ClassZ
    }
}