// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextGenSoftware.OASIS.API.Core.Enums;
using NextGenSoftware.OASIS.API.Providers.SQLLiteDBOASIS.Persistence.Context;

#nullable disable

namespace NextGenSoftware.OASIS.API.Providers.SQLLiteDBOASIS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220619144509_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("NextGenSoftware.OASIS.API.Providers.SQLLiteDBOASIS.Entities.AvatarDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("address");

                    b.Property<string>("Country")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("country");

                    b.Property<string>("County")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("county");

                    b.Property<Guid>("CreatedByAvatarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("created_by_avatar_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_date");

                    b.Property<OASISType>("CreatedOASISType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_oasis_type");

                    b.Property<ProviderType>("CreatedProviderType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_provider_type");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("DATETIME")
                        .HasColumnName("dob");

                    b.Property<Guid>("DeletedByAvatarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("deleted_by_avatar_id");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(300)")
                        .HasColumnName("description");

                    b.Property<DimensionLevel>("DimensionLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dimension_level");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("email");

                    b.Property<ConsoleColor>("FavouriteColour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("favourite_colour");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsChanged")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_changed");

                    b.Property<bool>("IsNewHolon")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_new_holon");

                    b.Property<bool>("IsSaving")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_saving");

                    b.Property<int>("Karma")
                        .HasColumnType("INTEGER")
                        .HasColumnName("karma");

                    b.Property<string>("Landline")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("landline");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<string>("Mobile")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("mobile");

                    b.Property<string>("Model3D")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("model_3d");

                    b.Property<Guid>("ModifiedByAvatarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("modified_by_avatar_id");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("modified_date");

                    b.Property<Guid>("ParentCelestialBodyId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_celestial_body_id");

                    b.Property<Guid>("ParentCelestialSpaceId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_celestial_space_id");

                    b.Property<Guid>("ParentDimensionId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_dimension_id");

                    b.Property<Guid>("ParentGalaxyClusterId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_galaxy_cluster_id");

                    b.Property<Guid>("ParentGalaxyId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_galaxy_id");

                    b.Property<Guid>("ParentGrandSuperStarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_grand_super_star_id");

                    b.Property<Guid>("ParentGreatGrandSuperStarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_great_grand_super_star_id");

                    b.Property<Guid>("ParentHolonId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_holon_id");

                    b.Property<Guid>("ParentMoonId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_moon_id");

                    b.Property<Guid>("ParentMultiverseId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_multiverse_id");

                    b.Property<Guid>("ParentOmniverseId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_omniverse_id");

                    b.Property<Guid>("ParentPlanetId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_planet_id");

                    b.Property<Guid>("ParentSolarSystemId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_solar_system_id");

                    b.Property<Guid>("ParentStarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_star_id");

                    b.Property<Guid>("ParentSuperStarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_super_star_id");

                    b.Property<Guid>("ParentUniverseId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_universe_id");

                    b.Property<Guid>("ParentZomeId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_zome_Id");

                    b.Property<string>("Portrait")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("portrait");

                    b.Property<string>("Postcode")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("postcode");

                    b.Property<Guid>("PreviousVersionId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("previous_version_id");

                    b.Property<ConsoleColor>("STARCLIColour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("star_cli_colour");

                    b.Property<SubDimensionLevel>("SubDimensionLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sub_dimension_level");

                    b.Property<string>("Town")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("town");

                    b.Property<string>("UmaJson")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("uma_json");

                    b.Property<string>("Username")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("username");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("version_id");

                    b.Property<int>("XP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("Id", "Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "idx_avatar_dtl_id");

                    b.ToTable("avatar_details");
                });

            modelBuilder.Entity("NextGenSoftware.OASIS.API.Providers.SQLLiteDBOASIS.Entities.AvatarEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("avatar_id");

                    b.Property<bool>("AcceptTerms")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("accept_terms");

                    b.Property<AvatarType>("AvatarType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("avatar_type");

                    b.Property<Guid>("DeletedByAvatarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("deleted_by_avatar_id");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR(20)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("HolonId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("holon_id");

                    b.Property<bool>("IsBeamedIn")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_beamed_in");

                    b.Property<string>("JwtToken")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("jwt_token");

                    b.Property<DateTime?>("LastBeamedIn")
                        .HasColumnType("DATETIME")
                        .HasColumnName("last_beamed_in");

                    b.Property<DateTime?>("LastBeamedOut")
                        .HasColumnType("DATETIME")
                        .HasColumnName("last_beamed_out");

                    b.Property<string>("LastName")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("password");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("DATETIME")
                        .HasColumnName("password_reset");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("ResetToken")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("DATETIME")
                        .HasColumnName("reset_token_expires");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR(200)")
                        .HasColumnName("title");

                    b.Property<string>("Username")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("username");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("verification_token");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("DATETIME")
                        .HasColumnName("verified");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id", "AvatarId");

                    b.HasIndex("Id", "AvatarId", "Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "idx_avatar_id");

                    b.ToTable("avatars");
                });

            modelBuilder.Entity("NextGenSoftware.OASIS.API.Providers.SQLLiteDBOASIS.Entities.HolonEntity", b =>
                {
                    b.Property<Guid>("HolonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("holon_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_date");

                    b.Property<OASISType>("CreatedOASISType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_oasis_type");

                    b.Property<ProviderType>("CreatedProviderType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_provider_type");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(300)")
                        .HasColumnName("description");

                    b.Property<DimensionLevel>("DimensionLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dimension_level");

                    b.Property<Guid>("Id")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsChanged")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_changed");

                    b.Property<bool>("IsNewHolon")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_new_holon");

                    b.Property<bool>("IsSaving")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_saving");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ParentCelestialBodyId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_celestial_body_id");

                    b.Property<Guid>("ParentCelestialSpaceId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_celestial_space_id");

                    b.Property<Guid>("ParentDimensionId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_dimension_id");

                    b.Property<Guid>("ParentGalaxyClusterId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_galaxy_cluster_id");

                    b.Property<Guid>("ParentGalaxyId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_galaxy_id");

                    b.Property<Guid>("ParentGrandSuperStarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_grand_super_star_id");

                    b.Property<Guid>("ParentGreatGrandSuperStarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_great_grand_super_star_id");

                    b.Property<Guid>("ParentHolonId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_holon_id");

                    b.Property<Guid>("ParentMoonId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_moon_id");

                    b.Property<Guid>("ParentMultiverseId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_multiverse_id");

                    b.Property<Guid>("ParentOmniverseId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_omniverse_id");

                    b.Property<Guid>("ParentPlanetId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_planet_id");

                    b.Property<Guid>("ParentSolarSystemId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_solar_system_id");

                    b.Property<Guid>("ParentStarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_star_id");

                    b.Property<Guid>("ParentSuperStarId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_super_star_id");

                    b.Property<Guid>("ParentUniverseId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_universe_id");

                    b.Property<Guid>("ParentZomeId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("parent_zome_id");

                    b.Property<Guid>("PreviousVersionId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("previous_version_id");

                    b.Property<SubDimensionLevel>("SubDimensionLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sub_dimension_level");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("NVARCHAR(64)")
                        .HasColumnName("version_id");

                    b.HasKey("HolonId");

                    b.HasIndex("HolonId")
                        .IsUnique();

                    b.HasIndex(new[] { "HolonId" }, "idx_holon_id");

                    b.ToTable("holons");
                });
#pragma warning restore 612, 618
        }
    }
}
